=== dagrlo/master/Lenguajes de marcado/examenes/de clase/otra vez/e1.dtd
<!ELEMENT bodegas (bodega*)>
<!ELEMENT bodega (nombre,ubicacion, vinos*)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT ubicacion (comAut,provincia,den)>
<!ELEMENT comAut (#PCDATA)>
<!ELEMENT provincia (#PCDATA)>
<!ELEMENT den (#PCDATA)>
<!ELEMENT vinos (nombreVino, tiempo, clasificacion, premios*)>
<!ELEMENT nombreVino (#PCDATA)>
<!ELEMENT tiempo (#PCDATA)>
<!ELEMENT clasificacion (tranquilo?)>
<!ATTLIST clasificacion especial (mistelas|espumosos) #IMPLIED>
<!ELEMENT tranquilo EMPTY>
<!ATTLIST tranquilo tipo (blancos|rosados|tintos) #REQUIRED>
<!ATTLIST tranquilo maduracion (joven|crianza|reserva) #REQUIRED>
<!ELEMENT premios (nombrePremio, fecha)>
<!ELEMENT nombrePremio (#PCDATA)>
<!ELEMENT fecha (#PCDATA)>

=== dagrlo/master/Lenguajes de marcado/examenes/de clase/otra vez/e1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE bodegas SYSTEM "e1.dtd">

<bodegas>
  <bodega>
    <nombre>B1</nombre>
    <ubicacion>
      <comAut>Com1</comAut>
      <provincia>P1</provincia>
      <den>D1</den>
    </ubicacion>
    <vinos>
      <nombreVino>Vinacho</nombreVino>
      <tiempo>111</tiempo>
      <clasificacion especial="mistelas"/>
    </vinos>
    <vinos>
      <nombreVino>Carton</nombreVino>
      <tiempo>432</tiempo>
      <clasificacion>
        <tranquilo tipo="blancos" maduracion="joven"/>
      </clasificacion>
      <premios>      
        <nombrePremio>kk</nombrePremio>
        <fecha>999</fecha>
      </premios>
    </vinos>
  </bodega>
</bodegas>
