=== dagrlo/master/Lenguajes de marcado/actividad7/comentarios.dtd
<!ELEMENT comentarios (entrada*)>
<!ELEMENT entrada (titulo, precio, comentario)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT precio (#PCDATA)>
<!ELEMENT comentario (#PCDATA)>

=== dagrlo/master/Lenguajes de marcado/actividad7/comentarios.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE comentarios SYSTEM "comentarios.dtd">
<comentarios>
<entrada>
<titulo>Data on the Web</titulo>
<precio>34.95</precio>
<comentario>
Un libro muy bueno sobre bases de datos.
</comentario>
</entrada>
<entrada>
<titulo>Advanced Programming in the Unix
environment</titulo>
<precio>65.95</precio>
<comentario>
Un libro claro y detallado de programación en UNIX.
</comentario>
</entrada>
<entrada>
<titulo>TCP/IP Illustrated</titulo>
<precio>65.95</precio>
<comentario>
Uno de los mejores libros de TCP/IP
</comentario>
</entrada>
</comentarios>
