<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE sistemaSolar [
<!ELEMENT sistemaSolar (cuerpo*)>
<!ELEMENT cuerpo ((planeta|satelite|asteroide)+)>
<!ELEMENT planeta (#PCDATA)>
<!ELEMENT satelite (#PCDATA)>
<!ELEMENT asteroide (#PCDATA)>
]>
<sistemaSolar>
<cuerpo>
<planeta>Tierra</planeta>

</cuerpo>
<cuerpo>
<satelite>Luna</satelite>
</cuerpo>
<cuerpo>
<asteroide>Ceres</asteroide>
</cuerpo>

</sistemaSolar>

<!-- en cuerpo 1 o mas del mismo tipo-->
<!--la entrada ceres debe ir dwentro de un cuerpo --> 


