<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE partidos [
<!ELEMENT partidos (partido*)>
<!ELEMENT partido (local, visitante, goles_local, goles_visitante)>
<!ELEMENT local (#PCDATA)>
<!ELEMENT visitante (#PCDATA)>
<!ELEMENT goles_local (#PCDATA)>
<!ELEMENT goles_visitante (#PCDATA)>
]>

<partidos>
	<partido>
		<local>Nottingham</local>
		<visitante>Inter</visitante>
		<goles_local>0</goles_local>
		<goles_visitante>1</goles_visitante>
	</partido>
	<partido>
		<local>Vodka</local>
		<visitante>Sparta</visitante>
		<goles_local>3</goles_local>
		<goles_visitante>3</goles_visitante>
	</partido>
	<partido>
		<local>Water</local>
		<visitante>Grifo</visitante>
		<goles_local>4</goles_local>
		<goles_visitante>2</goles_visitante>
	</partido>
</partidos>




