<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE efemerides [
<!ELEMENT efemerides (efemeride*)>
<!ELEMENT efemeride (fecha, hecho)>
<!ELEMENT fecha (#PCDATA)>
<!ELEMENT hecho (#PCDATA)>
]>
<efemerides>
<efemeride>
<fecha>20 de julio de 1969</fecha>
<hecho>Llegada del hombre a la Luna</hecho>
</efemeride>
<efemeride>
<fecha>12 de octubre de 1492</fecha>
<hecho>Llegada de Colón a América</hecho>
</efemeride>
<efemeride>
<fecha>6 de abril de 1909</fecha>
<hecho>llegada de Robert Peary al Polo Norte</hecho>
</efemeride>
</efemerides>

<!-- hay que poner efemeride* para poder poner varios-->
<!--declarar fecha y hecho  --> 


