<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE vuelos [
<!ELEMENT vuelos (vuelo*)>
<!ELEMENT vuelo (origen, destino)>
<!ELEMENT origen (#PCDATA)>
<!ELEMENT destino (#PCDATA)>
]>
<vuelos>
<vuelo>
<origen>Valencia (VLC)</origen>
<destino>Londres Heathrow (LHR)</destino>
</vuelo>
<vuelo>
<origen>Paris Charles de Gaulle (CDG)</origen>
<destino>Berlín Schönefeld (SFX)</destino>

</vuelo>
</vuelos>
<!-- en la 2 entrada va primero origen -->



