<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE contabilidad [
<!ELEMENT contabilidad (apunte*)>
<!ELEMENT apunte ((ingreso | gasto)*,fecha,cantidad,concepto)>
<!ELEMENT ingreso EMPTY>
<!ELEMENT gasto EMPTY>
<!ELEMENT fecha (#PCDATA)>
<!ELEMENT cantidad (#PCDATA)>
<!ELEMENT concepto (#PCDATA)>
]>

<contabilidad>

<apunte>
<ingreso />
<fecha>24 de febrero de 2011</fecha>
<cantidad>1800,00 ?</cantidad>
<concepto>Salario</concepto>
</apunte>


<apunte>
<gasto />
<fecha>28 de febrero de 2011</fecha>
<cantidad>74,25 ?</cantidad>
<concepto>Recibo luz</concepto>
</apunte>

</contabilidad>


<!--  contabilidad lleva dentro apuntes *-->
<!-- definir apunte. Gasto e ingreso son attrs-->






