=== dagrlo/master/Lenguajes de marcado/tema 1/ejercicios/ejemplo-agenda.dtd
<!ELEMENT agenda (persona)+>
<!ELEMENT persona (nombre, tlf,email+,(relaciones*)?)>
<!ATTLIST persona id ID #REQUIRED>
<!ATTLIST persona sexo (masculino|femenino) #REQUIRED>
<!ATTLIST relaciones nombre IDREFS #IMPLIED>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT tlf (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT relaciones EMPTY>

=== dagrlo/master/Lenguajes de marcado/tema 1/ejercicios/dtd_52.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE agenda SYSTEM "ejemplo-agenda.dtd">
<agenda>
<persona id="ricardo" sexo="masculino">
<nombre>Ricardo Borriquero</nombre>
<tlf>951345678</tlf>
<email>kkk</email>
<email>aaa</email>
<relaciones nombre="eva"/>
<relaciones nombre="lola"/>
</persona>
<persona id="eva" sexo="femenino">
<nombre>Eva Risto</nombre>
<tlf>955837659</tlf>
<email>aaa</email>
<relaciones nombre="lola"/>
<relaciones nombre="ricardo"/>
</persona>
<persona id="lola" sexo="femenino">
<nombre>Eva Risto</nombre>
<tlf>955837659</tlf>
<email>aaa</email>
<relaciones nombre="ricardo"/>
</persona>
</agenda>
