=== dagrlo/master/Lenguajes de marcado/examenes/de clase/e1.dtd
<!ELEMENT bodegas (bodega*)>
<!ELEMENT bodega (nombreBodega,comunidad,provincia,origen?,vinos*)>
<!ELEMENT nombreBodega (#PCDATA)>
<!ELEMENT comunidad (#PCDATA)>
<!ELEMENT provincia (#PCDATA)>
<!ELEMENT origen (#PCDATA)>
<!ELEMENT vinos (nombre, cosecha, clasificacion, premios*)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT cosecha (#PCDATA)>
<!ELEMENT clasificacion EMPTY>
<!ATTLIST clasificacion tranquiloTipo (blanco|rosado|tinto) #IMPLIED>
<!ATTLIST clasificacion tranquiloMaduracion (joven|crianza|reserva) #IMPLIED>
<!ATTLIST clasificacion especial (mistelas|espumosos) #IMPLIED>
<!ELEMENT premios (premio, cuando)>
<!ELEMENT premio (#PCDATA)>
<!ELEMENT cuando (#PCDATA)>

=== dagrlo/master/Lenguajes de marcado/examenes/de clase/e1.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE bodegas SYSTEM "e1.dtd">


<bodegas>
  <bodega>
    <nombreBodega>B1</nombreBodega>
    <comunidad>Comunidad 1</comunidad>
    <provincia>Provincia 1</provincia>
    <origen>Tiene origen</origen>
    <vinos>
      <nombre>V1</nombre>
      <cosecha>1234</cosecha>
      <clasificacion tranquiloTipo="blanco" tranquiloMaduracion="joven"/>      
    </vinos>            
    <vinos>
      <nombre>V2</nombre>
      <cosecha>999</cosecha>
      <clasificacion especial="mistelas"/>
      <premios>
        <premio>P1</premio>
        <cuando>222</cuando>
      </premios>
    </vinos>
   
  </bodega>
</bodegas>
