=== dagrlo/master/Lenguajes de marcado/tema 2/ejercicio3/FINAL/biblioteca.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">


<xsd:complexType name="TBibliotecario">

   <xsd:sequence>

      <xsd:element name="nombre" type="xsd:string"/>

      <xsd:element name="apellidos" type="xsd:string"/>

   </xsd:sequence>

</xsd:complexType>


<xsd:complexType name="TLibro">

   <xsd:sequence>

       <xsd:element name="numReg" type="xsd:ID"/>

       <xsd:element name="titulo" type="xsd:string"/>

       <xsd:element name="autores" type="xsd:string" minOccurs="1" maxOccurs="unbounded"/>

   </xsd:sequence>

</xsd:complexType>


<xsd:complexType name="TDireccion">

   <xsd:sequence>

      <xsd:element name="tipo" type="xsd:string"/>

      <xsd:element name="nombreCalle" type="xsd:string"/>

      <xsd:element name="numero" type="xsd:string"/>

      <xsd:element name="cp" type="xsd:integer"/>

      <xsd:element name="localidad" type="xsd:string"/>

      <xsd:element name="provincia" type="xsd:string"/>

   </xsd:sequence>

</xsd:complexType>


<xsd:complexType name="TSocio">

    <xsd:sequence>

       <xsd:element name="nombre" type="xsd:string"/>

       <xsd:element name="apellidos" type="xsd:string"/>

       <xsd:element name="telefono" type="xsd:string"/>

       <xsd:element name="direccion" type="TDireccion"/>

    </xsd:sequence>

</xsd:complexType>


<xsd:complexType name="TPrestamos">

    <xsd:sequence>

        <xsd:element name="fechaP" type="xsd:date" minOccurs="1" maxOccurs="1"/>

        <xsd:element name="fechaD" type="xsd:date" minOccurs="0" maxOccurs="1"/>

        <xsd:element name="bibliotecario" type="xsd:string"/>

        <xsd:element name="libros" type="xsd:string" minOccurs="1" maxOccurs="3"/>

    </xsd:sequence>

</xsd:complexType>


<xsd:element name="biblioteca">

   <xsd:complexType>

      <xsd:sequence>

         <xsd:element name="bibliotecario" type="TBibliotecario"/>

         <xsd:element name="libros" type="TLibro" minOccurs="1" maxOccurs="unbounded"/>

         <xsd:element name="socios" type="TSocio" minOccurs="1" maxOccurs="unbounded"/>

         <xsd:element name="prestamos" type="TPrestamos"/>

      </xsd:sequence>

   </xsd:complexType>

</xsd:element>

</xsd:schema>

=== dagrlo/master/Lenguajes de marcado/tema 2/ejercicio3/bibliotecaInclude.xml
<?xml version="1.0" encoding="UTF-8"?>

<biblioteca  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="biblioteca.xsd" >


     <bibliotecario>

        <nombre>Pepe</nombre>
      

        <apellidos>Bibliotecas</apellidos>

     </bibliotecario>

     

     <libros>

        <numReg>l1</numReg>

        <titulo>Blade Runner</titulo>

        <autores>Philip K. dick</autores>

     </libros>

     

     <libros>
        <numReg>l2</numReg>
        <titulo>La Maquina Diferencial</titulo>
        <autores>Bruce Sterling</autores>
        <autores>William Gibson</autores>
     </libros>
     
     

     <socios>

         <nombre>Manolo</nombre>

         <apellidos>el del bombo</apellidos>

         <telefono>888</telefono>

         <direccion>

              <tipo>calle</tipo>

              <nombreCalle>Amarilla</nombreCalle>

              <numero>73</numero>

              <cp>73882</cp>

              <localidad>Valencia</localidad>

              <provincia>Valencia</provincia>

         </direccion>

     </socios>

     

     <socios>
         <nombre>socio 2</nombre>
         <apellidos>apsocio 1</apellidos>
         <telefono>888</telefono>
         <direccion>
              <tipo>calle</tipo>
              <nombreCalle>de la kk</nombreCalle>
              <numero>73</numero>
              <cp>73882</cp>
              <localidad>local</localidad>
              <provincia>prov</provincia>
         </direccion>
     </socios>


     <prestamos>

          <fechaP>2014-02-02</fechaP>

          <bibliotecario>Pepe</bibliotecario>

          <libros>Blade Runner</libros>

          <libros>La Maquina Diferencial</libros>

     </prestamos>

</biblioteca>
