=== dagrlo/master/Lenguajes de marcado/tema 1/Actividades/final/dtd_01.dtd
<!ELEMENT videoclub (peliculas*,videojuegos*, socios*,prestamos*)>
<!ELEMENT peliculas ( titulo, fecha, director, actores*)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT fecha (#PCDATA)>
<!ELEMENT director (#PCDATA)>
<!ELEMENT actores (#PCDATA)>
<!ATTLIST peliculas codigo ID #REQUIRED>
<!ELEMENT videojuegos ( nombre)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT tipo EMPTY>
<!ATTLIST videojuegos codigo ID #REQUIRED>
<!ATTLIST videojuegos tipo (play|wii) #REQUIRED>
<!ELEMENT socios ( nombre, edad)>
<!ELEMENT edad (#PCDATA)>
<!ATTLIST socios codigo ID #REQUIRED>
<!ELEMENT prestamos (fecha_alquiler, fecha_devolucion?)>
<!ELEMENT fecha_alquiler (#PCDATA)>
<!ELEMENT fecha_devolucion (#PCDATA)>
<!ATTLIST prestamos ref IDREF #REQUIRED>
<!ATTLIST prestamos ref_socio IDREF #REQUIRED>

=== dagrlo/master/Lenguajes de marcado/tema 1/Actividades/final/Videoclub01.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE videoclub SYSTEM "dtd_01.dtd">


<videoclub>
   <peliculas codigo="Peli001">
   	<titulo>Leolo</titulo>
   	<fecha>1992</fecha>
   	<director>Jean-Claude Lauzon</director>
   	<actores>
   		Maxime Collin, Gilbert Sicotte, Ginette Reno, Julien Guiomar, 
   		Giuditta Del Vecchio, Denys Arcand, Pierre Bourgault, Andrée Lachapelle, 
   		Yves Montmarquette, Lorne Brass, Roland Blouin, Geneviève Samson, 
   		Marie-Hélène Montpetit, Francis St-Onge
   	</actores>
   </peliculas>
   
    <peliculas codigo="Peli002">
   	<titulo>Akira</titulo>
   	<fecha>1988</fecha>
   	<director>Katsuhiro Ôtomo</director>
   	<actores>Anime</actores>
   </peliculas>

   <videojuegos codigo="Game001" tipo="play">
        <nombre>GTAIV </nombre>
   </videojuegos>
   
   <socios codigo="Soc001">
        <nombre>Paco Menéndez</nombre>
        <edad>49</edad>
   </socios>
   
   <prestamos ref="Peli001" ref_socio="Soc001">
          <fecha_alquiler>3-6-1492</fecha_alquiler>
				
   </prestamos>
   
   <prestamos ref="Game001" ref_socio="Soc001">
          <fecha_alquiler>573-6-2033</fecha_alquiler>				
   </prestamos>


</videoclub>
