=== dagrlo/master/Lenguajes de marcado/tema 1/Actividades/actividad_01/contabilidad/contabilidad.dtd
<!ELEMENT contabilidad (apunte*)>
<!ELEMENT apunte (fecha, cantidad, concepto)>
<!ELEMENT fecha EMPTY>
<!ELEMENT cantidad (#PCDATA)>
<!ELEMENT concepto (#PCDATA)>
<!ATTLIST apunte tipo (ingreso | gasto) #REQUIRED>
<!ATTLIST fecha dia CDATA #IMPLIED>
<!ATTLIST fecha mes CDATA #REQUIRED>
<!ATTLIST fecha anyo CDATA #REQUIRED>
<!ATTLIST cantidad moneda CDATA #REQUIRED>

=== dagrlo/master/Lenguajes de marcado/tema 1/Actividades/actividad_01/contabilidad/contabilidad.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE contabilidad SYSTEM "contabilidad.dtd">

<contabilidad>
	<apunte tipo="ingreso">
		<fecha dia="24" mes="febrero" anyo="2011"/>
		<cantidad moneda="?">1800</cantidad>
		<concepto>Salario</concepto>
	</apunte>
	
	<apunte tipo="gasto">
		<fecha mes="febrero" anyo="2011"/>
		<cantidad moneda="$">74,25</cantidad>
		<concepto>Recibo luz</concepto>
	</apunte>
	


</contabilidad>
